// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// main_NewModel1Clean
Rcpp::NumericVector main_NewModel1Clean(Rcpp::RObject odata);
RcppExport SEXP _methylclock_main_NewModel1Clean(SEXP odataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::RObject >::type odata(odataSEXP);
    rcpp_result_gen = Rcpp::wrap(main_NewModel1Clean(odata));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_methylclock_main_NewModel1Clean", (DL_FUNC) &_methylclock_main_NewModel1Clean, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_methylclock(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
